name: Build

on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: "ap-northeast-2"
  AWS_ROLE: "arn:aws:iam::724157050461:role/github-oidc"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install
        id: install
        run: pnpm i && pnpm i soar --force

      - name: Build
        run: pnpm build
