name: Lint CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get Node cache
        uses: actions/cache@v2
        id: get-node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.get-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint JS
        env:
          NODE_ENV: test
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint formatting
        run: npm run lint:format

      - name: Check types
        run: npm run type-check
